pipeline:
    build:
        image: alpine
        commands:
          - apk update
          - apk add npm curl jq
          - sudo npm install -g markdownlint-cli
          - markdownlint README.md
