kind: pipeline
name: default

steps:
  
- name: Packet Markdown Standard Test
  image: alpine
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
  commands:
  - apk update
  - apk add npm curl jq
  - npm install -g markdownlint-cli
  - markdownlint README.md
